#include "globals.h"

uint16_t LDR_RAW;
bool BLOCK_NAVIGATION = false;
float HUM_OFFSET;
float TEMP_OFFSET = -9;
float CURRENT_HUM;
float CURRENT_LUX;
float CURRENT_TEMP;
bool IS_CELSIUS;
bool SENSOR_READING = true;
uint8_t BATTERY_PERCENT;
uint16_t BATTERY_RAW;
int BRIGHTNESS = 120;
int BRIGHTNESS_PERCENT;
bool MATRIX_OFF;
uint8_t MIN_BRIGHTNESS = 2;
uint8_t MAX_BRIGHTNESS = 180;
